---
# deploy prod
- name: deploy coolstore in {{ project_prod }}
  shell: "{{ openshift_cli }} process -f {{ deployments_template }} --param=APP_VERSION=prod --param=HOSTNAME_SUFFIX={{ project_prod }}.{{ hostname_suffix }} -n {{ project_prod }} | {{ openshift_cli }} create -f - -n {{ project_prod }}"
  ignore_errors: true

- name: deploy netflix oss in {{ project_prod }}
  shell: "{{ openshift_cli }} create -f {{ netflix_oss_template }} -n {{ project_prod }}"
  ignore_errors: true

- name: deploy inventory blue and green deployments in {{ project_prod }}
  shell: |
    {{ openshift_cli }} delete all,pvc -l app=inventory --now --ignore-not-found -n {{ project_prod }}
    {{ openshift_cli }} process -f {{ bluegreen_deployment_template }} --param=APP_VERSION_BLUE=prod-blue --param=APP_VERSION_GREEN=prod-green --param=HOSTNAME_SUFFIX={{ project_prod }}.{{ hostname_suffix }} -n {{ project_prod }} | {{ openshift_cli }} create -f - -n {{ project_prod }}

- name: prune deployments in {{ project_prod }}
  shell: "{{ openshift_cli }} delete dc,svc,route,pvc,cm -l {{ prune_deployments_selector_prod }} -n {{ project_prod }}"
  ignore_errors: true
  when:
  - prune_deployments_selector_stage is defined
  - prune_deployments_selector_stage is not none
  - prune_deployments_selector_stage|trim() != ""

# remove persistent storage
- import_tasks: make_ephemeral.yml
  vars:
    project_name: "{{ project_prod }}"
  when: ephemeral

