---
# playbook for deploying a pipeline to pre-build coolstore container images and 
# reduce the deploy time for the demo
# 
# Usage: ansible-playbook imagebuild-pipeline.yml

- name: Create CoolStore Image Build Pipeline to Pre-Build Images
  hosts: localhost
  gather_facts: false
  run_once: true
  vars:
    project_name: coolstore-image-builds
    github_account: jbossdemocentral
    github_ref: ocp-3.10
    maven_mirror_url: https://mirror.openshift.com/nexus/content/groups/public/
    pipeline_template: https://raw.githubusercontent.com/{{ github_account }}/coolstore-microservice/{{ github_ref }}/openshift/templates/imagebuild-pipeline-template.yaml
  tasks:
  - include_role:
      name: openshift_common_facts
    vars:
      set_hostname_suffix: false

  - name: check if image builder project exists
    shell: "{{ openshift_cli }} get project {{ project_name }}"
    register: result
    ignore_errors: true
    changed_when: false

  - name: create image builder project {{ project_name }}
    shell: "{{ openshift_cli }} new-project {{ project_name }} --description='DO NOT REMOVE THIS PROJECT. NEEDED FOR COOLSTORE DEMO'"
    ignore_errors: true
    when: result is failed

  - import_role:
      name: openshift_jenkins
    vars:
      project_name: "{{ project_name }}"
      jenkins_max_cpu: 2

  - name: create coolstore image build pipeline
    shell: "{{ openshift_cli }} process -f {{ pipeline_template }} --param=GITHUB_ACCOUNT={{ github_account }} --param=GITHUB_REF={{ github_ref }} --param=MAVEN_MIRROR_URL={{ maven_mirror_url }} -n {{ project_name }} | {{ openshift_cli }} create -f - -n {{ project_name }}"
    ignore_errors: true