---
- name: Deploy Coolstore Microservices Demo - CI/CD with JBoss EAP
  hosts: localhost
  gather_facts: false
  run_once: true
  vars_files:
    - demo_vars/msa-cicd-eap/all

  tasks:
    - include_role:
        name: openshift_common_facts
      tags:
        - cicd
        - guides
        - demo

    - import_role:
        name: openshift_gogs
      vars:
        project_name: "{{ project_cicd }}"
        project_display_name: "{{ project_cicd_name }}"
        project_desc: "{{ project_cicd_desc }}"
        project_annotations: "demo=demo-modern-arch-{{ project_suffix }}"
        gogs_route: "gogs-{{ project_cicd }}.{{ apps_hostname_suffix }}"
        gogs_deploy_retry_count: 60
        gogs_deploy_retry_delay: 30
      tags: cicd

    - import_role:
        name: openshift_sonatype_nexus
      vars:
        project_name: "{{ project_cicd }}"
      when: >
        maven_mirror_url is not defined or
        maven_mirror_url is none or
        maven_mirror_url|trim() == ""
      tags: cicd

    - import_role:
        name: openshift_jenkins
      vars:
        project_name: "{{ project_cicd }}"
      tags: cicd

    - import_role:
        name: openshift_workshopper
      vars:
        project_name: "{{ project_cicd }}"
        workshopper_workshop_urls: "{{ workshopper_content_url_prefix }}/demo-cicd-eap-full.yml"
        workshopper_env_vars:
          PROJECT_SUFFIX: "{{ project_suffix }}"
          GOGS_URL: http://gogs-{{ project_cicd }}.{{ apps_hostname_suffix }}
          GOGS_DEV_REPO_URL_PREFIX: http://gogs-{{ project_cicd }}.{{ apps_hostname_suffix }}/{{ gogs_user }}/coolstore-microservice
          JENKINS_URL: http://jenkins-{{ project_prod }}.{{ apps_hostname_suffix }}
          COOLSTORE_WEB_PROD_URL: http://web-ui-{{ project_prod }}.{{ apps_hostname_suffix }}
          HYSTRIX_PROD_URL: http://hystrix-dashboard-{{ project_prod }}.{{ apps_hostname_suffix }}
          GOGS_DEV_USER: "{{ gogs_user }}"
          GOGS_DEV_PASSWORD: "{{ gogs_password }}"
          GOGS_REVIEWER_USER: "{{ gogs_admin_user }}"
          GOGS_REVIEWER_PASSWORD: "{{ gogs_admin_password }}"
      when: deploy_guides
      tags: guides

    # deploy eclipse che
    - import_role:
        name: openshift_eclipse_che
      vars:
        project_name: "{{ project_cicd }}"
        che_version: "latest"
        route_suffix: "{{ apps_hostname_suffix }}"
      tags: eclipse-che

    # deploy coolstore
    - import_role:
        name: openshift_coolstore
      vars:
        project_annotations: "demo=demo-msa-cicd-eap-{{ project_suffix }}"
        hostname_suffix: "{{ apps_hostname_suffix }}"
        gogs_hostname: "gogs-{{ project_cicd }}.{{ apps_hostname_suffix }}"
        prune_deployments_selector_prod: ""
        prune_deployments_selector_stage: "comp-required!=true,app!=inventory"
        src_github_account: "{{ github_account }}"
        src_github_ref: stable-{{ github_ref }}

      tags: demo

    # verify deployed successfully
    - include_tasks: verify_all.yml
      tags: verify